#!/usr/bin/env bash

# Rename original config file with postfix tilde and make it read only
# Yu Shiyang <yu.shiyang@gnayihs.uy>

file="$1"
if [ -e "$file"~ ]; then
	echo "Error: tilde: $file~ already exists" >&2
else
	if [ -d "$file" ]; then
		while true; do
			read -p "$file is a directory. Copy contents recursively? [yes/NO] " prompt
			case $prompt in
				[Yy]* )
					mv "$file" "$file"~ && cp -a "$file"~ "$file" && chmod -R --preserve-root a-rx,a+X "$file"~
					break
				;;
				[Nn]* )
					break
				;;
				* )
					printf "Please answer 'yes' or 'no'. "
				;;
			esac
		done
	elif [ -f "$file" ]; then
		mv "$file" "$file"~ && cp -a "$file"~ "$file" && chmod a-rx "$file"~
	else
		echo "Error: tilde: $file is not a file or a directory" >&2
	fi
fi
